[project]
name = "polyhe"
version = "1.0.2"
description = "Simple & easy Homomorphic Encryption"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [{ name = "Miguel Ángel Prosper", email = "mprosper@uji.es" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities"
]
keywords = ["Homomorphic", "Encryption", "Python"]
urls = { Homepage = "https://github.com/hpca-uji/polyhe", Repository = "https://github.com/hpca-uji/polyhe.git"}

requires-python = ">=3.13"
dependencies = [
    "numpy>=1.19.4",
    "openfhe>=1.4.0",
    "tenseal>=0.3.16",
    # "fhe-py-binding>=0.1.0"
]

[build-system]
requires = [
    "setuptools>=68.2.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "polyhe",
    "polyhe.*"
]