[project]
name = "polyhe"
version = "1.0.4"
description = "Simple and Pythonic Homomorphic Encryption"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [{ name = "Miguel Ángel Prosper", email = "mprosper@uji.es" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities"
]
keywords = ["Homomorphic", "Encryption", "Python"]
urls = { Homepage = "https://github.com/hpca-uji/polyhe", Repository = "https://github.com/hpca-uji/polyhe.git" }

requires-python = "~=3.13"
dependencies = [
    "numpy~=2.4",
    "openfhe~=1.4",
    "tenseal~=0.3",
]

[build-system]
requires = [
    "setuptools~=82.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "polyhe",
    "polyhe.*"
]